#
#
    COMMENT = Custom Ports of FreeBSD

    SUBDIR += basicSoftware
    SUBDIR += develMeta
    SUBDIR += ffmpeg
    SUBDIR += freeports
    SUBDIR += updatePorts
    SUBDIR += vimConf

.include <bsd.port.subdir.mk>
