# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD$

PORTNAME=	basicSoftware
PORTVERSION=	1.6
CATEGORIES=	free
MASTER_SITES=	#
DISTFILES=	#

MAINTAINER=	gslin@gslin.org
COMMENT=	Basic software meta port

RUN_DEPENDS=	${LOCALBASE}/sbin/mtr:${PORTSDIR}/net/mtr \
		free-vimConf>=0:${PORTSDIR}/free/vimConf \
		gist>=0:${PORTSDIR}/www/gist \
		hwstat>=0:${PORTSDIR}/sysutils/hwstat \
		lftp>=0:${PORTSDIR}/ftp/lftp \
		most>=0:${PORTSDIR}/sysutils/most \
		pigz>=0:${PORTSDIR}/archivers/pigz \
		pkg_rmleaves>=0:${PORTSDIR}/ports-mgmt/pkg_rmleaves \
		portmaster>=0:${PORTSDIR}/ports-mgmt/portmaster \
		pstree>=0:${PORTSDIR}/sysutils/pstree \
		rsync>=0:${PORTSDIR}/net/rsync \
		screen>=0:${PORTSDIR}/sysutils/screen \
		tmux>=0:${PORTSDIR}/sysutils/tmux \
		w3m-m17n>=0:${PORTSDIR}/www/w3m-m17n \
		wget>=0:${PORTSDIR}/ftp/wget

NO_BUILD=	yes

do-install:
	@${DO_NADA}

.include <bsd.port.mk>
